version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ubuntu/app/step3/zip/   # ubuntu or ec2-user
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu   # ubuntu or ec2-user
    group: ubuntu

hooks:
  AfterInstall:
    - location: stop.sh # 엔진엑스와 연결되어 있지 않은 스프링 부트를 종료합니다.
      timeout: 60
      runas: ubuntu # ubuntu or ec2-user
  ApplicationStart:
    - location: start.sh # 엔진엑스와 연결되어 있지 않은 Port로 새 버전의 스프링 부트를 시작합니다.
      timeout: 60
      runas: ubuntu # ubuntu or ec2-user
  ValidateService:
    - location: health.sh # 새 스프링 부트가 정상적으로 실행됐는지 확인 합니다.
      timeout: 60
      runas: ubuntu # ubuntu or ec2-user
